/*
* generated by Xtext
*/
package de.dailab.vsdt.parser.antlr;

import java.io.InputStream;

import org.eclipse.xtext.parser.antlr.IAntlrTokenFileProvider;

public class VxlAntlrTokenFileProvider implements IAntlrTokenFileProvider {
	
	public InputStream getAntlrTokenFile() {
		ClassLoader classLoader = getClass().getClassLoader();
    	return classLoader.getResourceAsStream("de/dailab/vsdt/parser/antlr/internal/InternalVxl.tokens");
	}
}
