/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package jiacbeans.validation;

import jiacbeans.AgentBean;
import jiacbeans.JavaVariable;
import jiacbeans.Script;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link jiacbeans.Method}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface MethodValidator {
	boolean validate();

	boolean validateContent(String value);

	boolean validateReturnType(String value);


	boolean validateParameters(EList<JavaVariable> value);

	boolean validateName(String value);

	boolean validateIsStatic(boolean value);

	boolean validateVisibility(int value);

	boolean validateContent(Script value);

	boolean validateAttributes(EList<JavaVariable> value);

	boolean validateReturnType(Class<?> value);

	boolean validateEReference0(AgentBean value);
}
