/**
 * <copyright>
 * </copyright>
 *
 * $Id$
 */
package jiacbeans.validation;

import java.util.Map;

import jiacbeans.Script;
import jiacbeans.Sequence;

import org.eclipse.emf.common.util.EList;

/**
 * A sample validator interface for {@link jiacbeans.TryCatch}.
 * This doesn't really do anything, and it's not a real EMF artifact.
 * It was generated by the org.eclipse.emf.examples.generator.validator plug-in to illustrate how EMF's code generator can be extended.
 * This can be disabled with -vmargs -Dorg.eclipse.emf.examples.generator.validator=false.
 */
public interface TryCatchValidator {
	boolean validate();

	boolean validateTry(Script value);
	boolean validateCatches(Map<String, Script> value);

	boolean validateCatches(EList<Map<String, Sequence>> value);
	boolean validateFinally(Script value);
}
