/*
 * generated by Xtext
 */
package de.dailab.vsdt.vxl.formatting;

import org.eclipse.xtext.formatting.impl.AbstractDeclarativeFormatter;
import org.eclipse.xtext.formatting.impl.FormattingConfig;

/**
 * This class contains custom formatting description.
 * 
 * see : http://www.eclipse.org/Xtext/documentation/latest/xtext.html#formatting
 * on how and when to use it 
 * 
 * Also see {@link org.eclipse.xtext.xtext.XtextFormattingTokenSerializer} as an example
 */
public class VxlFormatter extends AbstractDeclarativeFormatter {
	
	@Override
	protected void configureFormatting(FormattingConfig c) {
//		de.dailab.vsdt.vxl.services.VxlGrammarAccess f = (de.dailab.vsdt.vxl.services.VxlGrammarAccess) getGrammarAccess();

		//...
	}
}
