<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<wsdl:definitions xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://service.dailab.de/Logging/" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" name="Logging" targetNamespace="http://service.dailab.de/Logging/">

  <wsdl:message name="LogMessage">
    <wsdl:part name="message" type="xsd:string"/>
    <wsdl:part name="level" type="xsd:integer"/>
  </wsdl:message>
  
  <wsdl:portType name="LoggingPT">
    <wsdl:operation name="log">
      <wsdl:input message="tns:LogMessage"/>
    </wsdl:operation>
  </wsdl:portType>

  <wsdl:binding name="Logging" type="tns:LoggingPT">
  	<soap:binding style="rpc" transport="http://schemas.xmlsoap.org/soap/http"/>
  	<wsdl:operation name="log">
  		<soap:operation soapAction="http://service.dailab.de/Logging/log"/>
  		<wsdl:input>
	 		<soap:body namespace="http://service.dailab.de/Logging/" use="literal"/>
  		</wsdl:input>
  		<wsdl:output>
  			<soap:body namespace="http://service.dailab.de/Logging/" use="literal"/>
  		</wsdl:output>
  	</wsdl:operation>
  </wsdl:binding>
  
  <wsdl:service name="LoggingService">
    <wsdl:port binding="tns:Logging" name="LoggingPort">
      <soap:address location="http://localhost:8080/LoggingWS/services/LoggingPort"/>
    </wsdl:port>
  </wsdl:service>
</wsdl:definitions>
