/*
 * generated by Xtext
 */
package de.dailab.vsdt.vxl;

/**
 * Use this class to register components to be used within the IDE.
 */
public class VxlRuntimeModule extends de.dailab.vsdt.vxl.AbstractVxlRuntimeModule {

}
