<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="vxl"
    nsURI="http://www.dailab.de/vsdt/vxl/Vxl" nsPrefix="vxl">
  <eClassifiers xsi:type="ecore:EClass" name="Term">
    <eStructuralFeatures xsi:type="ecore:EReference" name="head" eType="#//Head" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="tail" eType="#//Tail" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Head"/>
  <eClassifiers xsi:type="ecore:EClass" name="Tail">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="operator" eType="#//Operator"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BracketTerm" eSuperTypes="#//Head">
    <eStructuralFeatures xsi:type="ecore:EReference" name="term" eType="#//Term" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Negation" eSuperTypes="#//Head">
    <eStructuralFeatures xsi:type="ecore:EReference" name="head" eType="#//Head" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Minus" eSuperTypes="#//Head">
    <eStructuralFeatures xsi:type="ecore:EReference" name="head" eType="#//Head" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Atom" eSuperTypes="#//Head"/>
  <eClassifiers xsi:type="ecore:EClass" name="Variable" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessor" eType="#//Accessor"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Accessor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessor" eType="#//Accessor"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ArrayAccessor" eSuperTypes="#//Accessor">
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//Term"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FieldAccessor" eSuperTypes="#//Accessor">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Value" eSuperTypes="#//Atom">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="const" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringConst" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="NumericConst" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="BooleanConst" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EClass" name="NullConst" eSuperTypes="#//Value"/>
  <eClassifiers xsi:type="ecore:EEnum" name="Operator">
    <eLiterals name="LT" literal="&lt;"/>
    <eLiterals name="LE" value="1" literal="&lt;="/>
    <eLiterals name="EQ" value="2" literal="=="/>
    <eLiterals name="NEQ" value="3" literal="!="/>
    <eLiterals name="GT" value="4" literal=">"/>
    <eLiterals name="GE" value="5" literal=">="/>
    <eLiterals name="ADD" value="6" literal="+"/>
    <eLiterals name="SUB" value="7" literal="-"/>
    <eLiterals name="MULT" value="8" literal="*"/>
    <eLiterals name="DIV" value="9" literal="/"/>
    <eLiterals name="MOD" value="10" literal="%"/>
    <eLiterals name="AND" value="11" literal="and"/>
    <eLiterals name="OR" value="12" literal="or"/>
    <eLiterals name="CONCAT" value="13" literal="++"/>
  </eClassifiers>
</ecore:EPackage>
