/*
 * generated by Xtext
 */
package de.dailab.vsdt.vxl;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class VxlRuntimeModule extends de.dailab.vsdt.vxl.AbstractVxlRuntimeModule {

}
