/*
* generated by Xtext
*/
package de.dailab.vsdt.vxl.parser.antlr;

import org.antlr.runtime.ANTLRInputStream;
import org.eclipse.xtext.parser.antlr.ITokenDefProvider;
import org.eclipse.xtext.parser.IParseResult;
import org.eclipse.xtext.parser.ParseException;
import org.eclipse.xtext.parser.antlr.XtextTokenStream;

import com.google.inject.Inject;

import de.dailab.vsdt.vxl.services.VxlGrammarAccess;

public class VxlParser extends org.eclipse.xtext.parser.antlr.AbstractAntlrParser {
	
	@Inject 
    protected ITokenDefProvider antlrTokenDefProvider;
	
	@Inject
	private VxlGrammarAccess grammarAccess;
	
	@Override
	protected IParseResult parse(String ruleName, ANTLRInputStream in) {
		de.dailab.vsdt.vxl.parser.antlr.internal.InternalVxlLexer lexer = new de.dailab.vsdt.vxl.parser.antlr.internal.InternalVxlLexer(in);
		XtextTokenStream stream = new XtextTokenStream(lexer, antlrTokenDefProvider);
		stream.setInitialHiddenTokens("RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT");
		de.dailab.vsdt.vxl.parser.antlr.internal.InternalVxlParser parser = new de.dailab.vsdt.vxl.parser.antlr.internal.InternalVxlParser(
				stream, getElementFactory(), grammarAccess);
		parser.setTokenTypeMap(antlrTokenDefProvider.getTokenDefMap());
		try {
			if(ruleName != null)
				return parser.parse(ruleName);
			return parser.parse();
		} catch (Exception re) {
			throw new ParseException(re.getMessage(),re);
		}
	}
	
	@Override 
	protected String getDefaultRuleName() {
		return "Term";
	}
	
	public VxlGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(VxlGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
